/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.ClienteDAO;
import MODEL.Cliente;
import MODEL.ClienteContato;
import MODEL.ClienteEndereco;
import MODEL.ClienteFisica;
import MODEL.ClienteJuridica;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kaynnan
 */
public class ClienteVIEW extends javax.swing.JInternalFrame {

    Cliente cliente;
    ClienteContato cliContato;
    ClienteEndereco cliEndereco;
    ClienteFisica cliFisica;
    ClienteJuridica cliJuridica;
    ClienteDAO clienteDAO;

    /**
     * Creates new form ClienteFisicaVIEW
     */
    public ClienteVIEW() {
        initComponents();
        this.setVisible(true);
        //btnAlterar.setEnabled(false);
        //btnBuscar.setEnabled(false);
        //btnExcluir.setEnabled(false);
        //btnSalvar.setEnabled(false);
        //btnCancelarJuridica.setEnabled(false);

        clienteDAO = new ClienteDAO();
    }

    public void limpaCamposFisica() {
        txtBairro.setText("");
        txtCEP.setText("");
        txtCPF.setText("");
        txtCelular.setText("");
        txtCidade.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtEstado.setSelectedItem("Selecione");
        txtNome.setText("");
        txtNumeroCasa.setText("");
        txtRG.setText("");
        txtTelefone.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_abas = new javax.swing.JTabbedPane();
        pnl_fisica = new javax.swing.JPanel();
        txtCelular = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        txtCEP = new javax.swing.JFormattedTextField();
        txtRG = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNumeroCasa = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEstado = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCancelarFisica = new javax.swing.JButton();
        pnl_Juridica = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtNomeJuridico = new javax.swing.JTextField();
        txtBairroJuridico = new javax.swing.JTextField();
        txtCidadeJuridico = new javax.swing.JTextField();
        txtEnderecoJuridico = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtEstadoJuridico = new javax.swing.JComboBox<>();
        txtNumeroJuridico = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtCEPJuridico = new javax.swing.JFormattedTextField();
        txtInscricaoEstadual = new javax.swing.JFormattedTextField();
        txtCelularJuridico = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        txtTelefoneJuridico = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtEmailJuridico = new javax.swing.JTextField();
        btnSalvarJuri = new javax.swing.JButton();
        btnBuscarJuri = new javax.swing.JButton();
        btnExcluirJuri = new javax.swing.JButton();
        btnNovoJuri = new javax.swing.JButton();
        btnAlterarJuri = new javax.swing.JButton();
        btnCancelarJuridica = new javax.swing.JButton();

        setClosable(true);

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });

        try {
            txtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRGActionPerformed(evt);
            }
        });

        jLabel1.setText("Celular");

        jLabel2.setText("Telefone");

        jLabel3.setText("CPF");

        jLabel4.setText("RG");

        jLabel5.setText("CEP");

        jLabel6.setText("Nome");

        jLabel7.setText("Endereço");

        jLabel8.setText("Bairro");

        jLabel10.setText("Número");

        jLabel11.setText("Cidade");

        jLabel12.setText("Estado");

        txtEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel13.setText("E-mail");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCancelarFisica.setText("Cancelar");
        btnCancelarFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFisicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_fisicaLayout = new javax.swing.GroupLayout(pnl_fisica);
        pnl_fisica.setLayout(pnl_fisicaLayout);
        pnl_fisicaLayout.setHorizontalGroup(
            pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_fisicaLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_fisicaLayout.createSequentialGroup()
                        .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_fisicaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(171, 171, 171))
                            .addGroup(pnl_fisicaLayout.createSequentialGroup()
                                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3))
                                .addGap(168, 168, 168))
                            .addGroup(pnl_fisicaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_fisicaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_fisicaLayout.createSequentialGroup()
                                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnl_fisicaLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(32, 32, 32)
                        .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_fisicaLayout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(txtCPF)
                                .addComponent(txtEndereco)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_fisicaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarFisica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        pnl_fisicaLayout.setVerticalGroup(
            pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_fisicaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(pnl_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnBuscar)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar))
                .addGap(18, 18, 18)
                .addComponent(btnCancelarFisica)
                .addGap(24, 24, 24))
        );

        pnl_abas.addTab("Pessoa Física", pnl_fisica);

        jLabel14.setText("Nome");

        jLabel15.setText("Endereço");

        jLabel17.setText("Cidade");

        jLabel18.setText("Bairro");

        jLabel19.setText("Estado");

        txtEstadoJuridico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel20.setText("Número");

        jLabel21.setText("CNPJ");

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel22.setText("Inscrição Estadual");

        jLabel23.setText("CEP");

        try {
            txtCEPJuridico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEPJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPJuridicoActionPerformed(evt);
            }
        });

        try {
            txtInscricaoEstadual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########.##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtInscricaoEstadual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInscricaoEstadualActionPerformed(evt);
            }
        });

        try {
            txtCelularJuridico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelularJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularJuridicoActionPerformed(evt);
            }
        });

        jLabel24.setText("Celular");

        try {
            txtTelefoneJuridico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel25.setText("Telefone");

        jLabel26.setText("E-mail");

        btnSalvarJuri.setText("Salvar");
        btnSalvarJuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarJuriActionPerformed(evt);
            }
        });

        btnBuscarJuri.setText("Buscar");
        btnBuscarJuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarJuriActionPerformed(evt);
            }
        });

        btnExcluirJuri.setText("Excluir");
        btnExcluirJuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirJuriActionPerformed(evt);
            }
        });

        btnNovoJuri.setText("Novo");
        btnNovoJuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoJuriActionPerformed(evt);
            }
        });

        btnAlterarJuri.setText("Alterar");
        btnAlterarJuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarJuriActionPerformed(evt);
            }
        });

        btnCancelarJuridica.setText("Cancelar");
        btnCancelarJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarJuridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_JuridicaLayout = new javax.swing.GroupLayout(pnl_Juridica);
        pnl_Juridica.setLayout(pnl_JuridicaLayout);
        pnl_JuridicaLayout.setHorizontalGroup(
            pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_JuridicaLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(15, 15, 15)
                .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_JuridicaLayout.createSequentialGroup()
                        .addComponent(txtNomeJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(pnl_JuridicaLayout.createSequentialGroup()
                        .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnderecoJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCNPJ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefoneJuridico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailJuridico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCEPJuridico)
                            .addComponent(txtInscricaoEstadual)
                            .addComponent(txtCelularJuridico, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtEstadoJuridico, 0, 110, Short.MAX_VALUE)
                            .addComponent(txtCidadeJuridico)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_JuridicaLayout.createSequentialGroup()
                        .addComponent(txtBairroJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_JuridicaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvarJuri, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarJuri, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirJuri, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNovoJuri, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlterarJuri, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        pnl_JuridicaLayout.setVerticalGroup(
            pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_JuridicaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNomeJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtBairroJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEnderecoJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstadoJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(txtNumeroJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtCEPJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(txtTelefoneJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtCelularJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtEmailJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(pnl_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarJuri)
                    .addComponent(btnBuscarJuri)
                    .addComponent(btnExcluirJuri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovoJuri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterarJuri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarJuridica)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pnl_abas.addTab("Pessoa Jurídica", pnl_Juridica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_abas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_abas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRGActionPerformed

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (txtBairro.getText().isEmpty() || txtCEP.getText().isEmpty()
                || txtCPF.getText().isEmpty() || txtCelular.getText().isEmpty()
                || txtCidade.getText().isEmpty() || txtEmail.getText().isEmpty()
                || txtEndereco.getText().isEmpty() || txtEstado.getSelectedItem() == "Selecione"
                || txtNome.getText().isEmpty() || txtNumeroCasa.getText().isEmpty()
                || txtRG.getText().isEmpty() || txtTelefone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            cliente = new Cliente();
            cliContato = new ClienteContato();
            cliEndereco = new ClienteEndereco();
            cliFisica = new ClienteFisica();

            cliFisica.setCpf(txtCPF.getText());
            cliFisica.setRg(txtRG.getText());

            cliContato.setCelular_cliente(txtCelular.getText());
            cliContato.setTelefone_cliente(txtTelefone.getText());
            cliContato.setEmail(txtEmail.getText());

            cliEndereco.setBairro(txtBairro.getText());
            cliEndereco.setCep(txtCEP.getText());
            cliEndereco.setCidade(txtCidade.getText());
            cliEndereco.setEstado((String) txtEstado.getSelectedItem());
            cliEndereco.setNumero(Integer.parseInt(txtNumeroCasa.getText()));
            cliEndereco.setRua(txtEndereco.getText());

            cliente.setNome_cliente(txtNome.getText());
            cliente.setTipo_cliente(1);

            try {
                clienteDAO.salvarFisica(cliente, cliFisica, cliEndereco, cliContato);

            } catch (SQLException ex) {
                Logger.getLogger(ClienteVIEW.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            limpaCamposFisica();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String valor = JOptionPane.showInputDialog(null, "Digite o código do cliente: ");

        cliente = new Cliente();
        cliente.setCod_cliente(Integer.parseInt(valor));

        int confirma = JOptionPane.showConfirmDialog(null, "Deseja excluir: ");

        if (confirma == 0) {
            try {
                clienteDAO.excluirFisica(cliente);
            } catch (SQLException ex) {
                Logger.getLogger(ClienteVIEW.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnSalvar.setEnabled(true);
        btnCancelarFisica.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String valor = JOptionPane.showInputDialog(null, "Digite o código do cliente: ");
        cliente = new Cliente();
        cliContato = new ClienteContato();
        cliEndereco = new ClienteEndereco();
        cliFisica = new ClienteFisica();

        cliente.setNome_cliente(txtNome.getText());
                
        cliFisica.setCpf(txtCPF.getText());
        cliFisica.setRg(txtRG.getText()); 
        
        cliEndereco.setRua(txtEndereco.getText());        
        cliEndereco.setNumero(Integer.parseInt(txtNumeroCasa.getText()));
        cliEndereco.setBairro(txtBairro.getText());
        cliEndereco.setCidade(txtCidade.getText());
        cliEndereco.setEstado((String) txtEstado.getSelectedItem());        
        cliEndereco.setCep(txtCEP.getText());
        
        cliContato.setTelefone_cliente(txtTelefone.getText());
        cliContato.setCelular_cliente(txtCelular.getText());        
        cliContato.setEmail(txtEmail.getText());
            
        
        cliente.setCod_cliente(Integer.parseInt(valor));
        try {
            clienteDAO.alterarFisica(cliente, cliFisica, cliEndereco, cliContato);
        } catch (SQLException ex) {
            Logger.getLogger(ClienteVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Alterado com sucesso !");
        limpaCamposFisica();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String valor = JOptionPane.showInputDialog(null, "Digite o código do cliente: ");
        cliente = new Cliente();
        cliFisica = new ClienteFisica();
        cliContato = new ClienteContato();
        cliEndereco = new ClienteEndereco();
        try {
            cliente = clienteDAO.buscarFisica(Integer.parseInt(valor));
        } catch (SQLException ex) {
            Logger.getLogger(ClienteVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Cliente */
        txtNome.setText(cliente.getNome_cliente());
        /* Endereço */
        txtCelular.setText(cliente.getCliContato().getCelular_cliente());
        txtTelefone.setText(cliente.getCliContato().getTelefone_cliente());
        txtEmail.setText(cliente.getCliContato().getEmail());
        /* Contato */
        txtBairro.setText(cliente.getCliEndereco().getBairro());
        txtCEP.setText(cliente.getCliEndereco().getCep());
        txtEndereco.setText(cliente.getCliEndereco().getRua());
        txtEstado.setSelectedItem(cliente.getCliEndereco().getEstado());
        txtCidade.setText(cliente.getCliEndereco().getCidade());
        txtNumeroCasa.setText(Integer.toString(cliente.getCliEndereco().getNumero()));
        /* Fisica */
        txtCPF.setText(cliente.getCliFisica().getCpf());
        txtRG.setText(cliente.getCliFisica().getRg());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCEPJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPJuridicoActionPerformed

    private void txtInscricaoEstadualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInscricaoEstadualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInscricaoEstadualActionPerformed

    private void txtCelularJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularJuridicoActionPerformed

    private void btnSalvarJuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarJuriActionPerformed

    }//GEN-LAST:event_btnSalvarJuriActionPerformed

    private void btnBuscarJuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarJuriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarJuriActionPerformed

    private void btnExcluirJuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirJuriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirJuriActionPerformed

    private void btnNovoJuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoJuriActionPerformed
        btnSalvar.setEnabled(true);
        btnCancelarJuridica.setEnabled(true);
    }//GEN-LAST:event_btnNovoJuriActionPerformed

    private void btnAlterarJuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarJuriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarJuriActionPerformed

    private void btnCancelarJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarJuridicaActionPerformed


    }//GEN-LAST:event_btnCancelarJuridicaActionPerformed

    private void btnCancelarFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFisicaActionPerformed
        limpaCamposFisica();
    }//GEN-LAST:event_btnCancelarFisicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlterarJuri;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarJuri;
    private javax.swing.JButton btnCancelarFisica;
    private javax.swing.JButton btnCancelarJuridica;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirJuri;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnNovoJuri;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarJuri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pnl_Juridica;
    private javax.swing.JTabbedPane pnl_abas;
    private javax.swing.JPanel pnl_fisica;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBairroJuridico;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCEPJuridico;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCelularJuridico;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCidadeJuridico;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailJuridico;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEnderecoJuridico;
    private javax.swing.JComboBox<String> txtEstado;
    private javax.swing.JComboBox<String> txtEstadoJuridico;
    private javax.swing.JFormattedTextField txtInscricaoEstadual;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeJuridico;
    private javax.swing.JTextField txtNumeroCasa;
    private javax.swing.JTextField txtNumeroJuridico;
    private javax.swing.JFormattedTextField txtRG;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JFormattedTextField txtTelefoneJuridico;
    // End of variables declaration//GEN-END:variables
}
