/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.FuncionarioDAO;
import MODEL.Contato;
import MODEL.Endereco;
import MODEL.Funcionario;
import MODEL.Usuario;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danis
 */
public class FuncionariosVIEW extends javax.swing.JFrame {

    FuncionarioDAO dao;
    Contato cont;
    Endereco end;
    Funcionario funcionario;

    public FuncionariosVIEW() throws ParseException {
        initComponents();
        this.setLocationRelativeTo(null);

        dao = new FuncionarioDAO();

        listarFuncionarios();
    }

    public void listarFuncionarios() throws ParseException {
        FuncionarioDAO dao = new FuncionarioDAO();

        List<Funcionario> lista = dao.listarFuncionarios();
        DefaultTableModel table = (DefaultTableModel) tabelaConsultaFuncionario.getModel();

        table.setNumRows(0);

        for (Funcionario f : lista) {
            table.addRow(new Object[]{
                f.getCod_funcionario(),
                f.getNome_funcionario(),
                f.getCpf_funcionario(),
                f.getRg_funcionario(),
                f.getData_admissao(),
                f.getStatus(),
                f.getNivel_acesso(),});
        }
    }

    public void fechaBotoes() {
        btnSalvarFuncionario.setEnabled(false);
        btnCancelarFuncionario.setEnabled(false);
        btnExcluirFuncionario.setEnabled(false);
    }

    public void fechaCampos() {
        txtBairro.setEnabled(false);
        txtCelularFuncionario.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidadeFuncionario.setEnabled(false);
        txtCpf.setEnabled(false);
        txtEmailFuncionario.setEnabled(false);
        txtNomeFuncionario.setEnabled(false);
        txtNumeroFuncionario.setEnabled(false);
        txtRg.setEnabled(false);
        txtRuaFuncionario.setEnabled(false);
        txtTelefoneFuncionario.setEnabled(false);
        txtEstado.setEnabled(false);
        txtNivelAcessoFuncionario.setEnabled(false);
        txtStatusFuncionario.setEnabled(false);
        txtSenha.setEnabled(false);
        txtCodigoFuncionario.setEnabled(false);
        txtCpf.setEnabled(false);
        txtRg.setEnabled(false);

    }

    public void abreCampos() {
        txtBairro.setEnabled(true);
        txtCelularFuncionario.setEnabled(true);
        txtCep.setEnabled(true);
        txtCidadeFuncionario.setEnabled(true);
        txtEmailFuncionario.setEnabled(true);
        txtNomeFuncionario.setEnabled(true);
        txtNumeroFuncionario.setEnabled(true);
        txtRuaFuncionario.setEnabled(true);
        txtTelefoneFuncionario.setEnabled(true);
        txtBuscarFuncionaro.setEnabled(true);
        txtEstado.setEnabled(true);
        txtNivelAcessoFuncionario.setEnabled(true);
        txtStatusFuncionario.setEnabled(true);
        txtSenha.setEnabled(true);
        txtCpf.setEnabled(true);
        txtRg.setEnabled(true);
    }

    public void limpaCampos() {
        txtBairro.setText("");
        txtCelularFuncionario.setText("");
        txtCep.setText("");
        txtCidadeFuncionario.setText("");

        txtCpf.setText("");
        txtEmailFuncionario.setText("");

        txtNomeFuncionario.setText("");
        txtNumeroFuncionario.setText("");
        txtRg.setText("");
        txtRuaFuncionario.setText("");
        txtTelefoneFuncionario.setText("");
        txtEstado.setSelectedItem("Selecione");
        txtCodigoFuncionario.setText("");
        txtNivelAcessoFuncionario.setText("");
        txtStatusFuncionario.setSelectedIndex(0);
        txtSenha.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtpConsultaFuncionaros = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnSalvarFuncionario = new javax.swing.JButton();
        btnCancelarFuncionario = new javax.swing.JButton();
        btnExcluirFuncionario = new javax.swing.JButton();
        btnAlterarFuncionario = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtCodigoFuncionario = new javax.swing.JTextField();
        txtNomeFuncionario = new javax.swing.JTextField();
        txtEmailFuncionario = new javax.swing.JTextField();
        txtRuaFuncionario = new javax.swing.JTextField();
        txtNumeroFuncionario = new javax.swing.JTextField();
        txtCidadeFuncionario = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtNivelAcessoFuncionario = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        txtCep = new javax.swing.JFormattedTextField();
        txtSenha = new javax.swing.JTextField();
        txtEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtTelefoneFuncionario = new javax.swing.JFormattedTextField();
        txtCelularFuncionario = new javax.swing.JFormattedTextField();
        txtStatusFuncionario = new javax.swing.JComboBox<>();
        jpConsultaFuncionario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarFuncionaro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsultaFuncionario = new javax.swing.JTable();
        btnNovoFuncionario = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionários");
        setMinimumSize(new java.awt.Dimension(1055, 510));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Funcionários");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(865, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jtpConsultaFuncionaros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtpConsultaFuncionarosStateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel2.setText("Código");

        jLabel8.setText("Senha");

        jLabel9.setText("Nome");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Auto Peças");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Barcelos");

        btnSalvarFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSalvarFuncionario.setText("Salvar");
        btnSalvarFuncionario.setEnabled(false);
        btnSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFuncionarioActionPerformed(evt);
            }
        });

        btnCancelarFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancelarFuncionario.setText("Cancelar");
        btnCancelarFuncionario.setEnabled(false);
        btnCancelarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFuncionarioActionPerformed(evt);
            }
        });

        btnExcluirFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnExcluirFuncionario.setText("Excluir");
        btnExcluirFuncionario.setEnabled(false);
        btnExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFuncionarioActionPerformed(evt);
            }
        });

        btnAlterarFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAlterarFuncionario.setText("Alterar");
        btnAlterarFuncionario.setEnabled(false);
        btnAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFuncionarioActionPerformed(evt);
            }
        });

        jLabel11.setText("Nível de Acesso");

        jLabel5.setText("CPF");

        jLabel6.setText("RG");

        jLabel12.setText("Status");

        jLabel13.setText("Telefone");

        jLabel14.setText("Celular");

        jLabel15.setText("E-mail");

        jLabel16.setText("Rua");

        jLabel17.setText("Número");

        jLabel18.setText("Bairro");

        jLabel21.setText("Cidade");

        jLabel22.setText("Estado");

        jLabel23.setText("CEP");

        txtCodigoFuncionario.setEnabled(false);
        txtCodigoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoFuncionarioActionPerformed(evt);
            }
        });

        txtNomeFuncionario.setEnabled(false);

        txtEmailFuncionario.setEnabled(false);

        txtRuaFuncionario.setEnabled(false);

        txtNumeroFuncionario.setEnabled(false);

        txtCidadeFuncionario.setEnabled(false);

        txtBairro.setEnabled(false);

        txtNivelAcessoFuncionario.setEnabled(false);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setEnabled(false);

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setEnabled(false);

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setEnabled(false);
        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });

        txtSenha.setEnabled(false);

        txtEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        txtEstado.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Dados Pessoais");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Dados de Contato");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Dados de Endereço");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setText("Dados de Acesso");

        try {
            txtTelefoneFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneFuncionario.setEnabled(false);
        txtTelefoneFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneFuncionarioActionPerformed(evt);
            }
        });

        try {
            txtCelularFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelularFuncionario.setEnabled(false);
        txtCelularFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularFuncionarioActionPerformed(evt);
            }
        });

        txtStatusFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Ativo", "Inativo" }));
        txtStatusFuncionario.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(119, 119, 119)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCelularFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(64, 64, 64))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNivelAcessoFuncionario)
                                    .addComponent(txtStatusFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAlterarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluirFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(194, 194, 194))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(609, 609, 609)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel21))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNumeroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRuaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(txtCidadeFuncionario)
                                        .addComponent(txtBairro))
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 79, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel24)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtRuaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel15)
                        .addComponent(txtEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumeroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCelularFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarFuncionario)
                            .addComponent(btnSalvarFuncionario)
                            .addComponent(btnCancelarFuncionario)
                            .addComponent(btnExcluirFuncionario)
                            .addComponent(jLabel20))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtNivelAcessoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtStatusFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );

        jtpConsultaFuncionaros.addTab("Dados funcionários", jPanel2);

        jpConsultaFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        jpConsultaFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpConsultaFuncionarioMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Buscar");

        txtBuscarFuncionaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarFuncionaroActionPerformed(evt);
            }
        });
        txtBuscarFuncionaro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarFuncionaroKeyPressed(evt);
            }
        });

        tabelaConsultaFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabelaConsultaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "RG", "Data de Admissão", "Status", "Nível de Acesso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaConsultaFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaConsultaFuncionario);

        javax.swing.GroupLayout jpConsultaFuncionarioLayout = new javax.swing.GroupLayout(jpConsultaFuncionario);
        jpConsultaFuncionario.setLayout(jpConsultaFuncionarioLayout);
        jpConsultaFuncionarioLayout.setHorizontalGroup(
            jpConsultaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConsultaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConsultaFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarFuncionaro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jpConsultaFuncionarioLayout.setVerticalGroup(
            jpConsultaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaFuncionarioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jpConsultaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBuscarFuncionaro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpConsultaFuncionaros.addTab("Consulta funcionários", jpConsultaFuncionario);

        btnNovoFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnNovoFuncionario.setText("Novo");
        btnNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpConsultaFuncionaros)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jtpConsultaFuncionaros, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovoFuncionario)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 433, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void txtCodigoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoFuncionarioActionPerformed

    private void btnAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFuncionarioActionPerformed
        if (txtNomeFuncionario.getText().isEmpty() || txtBairro.getText().isEmpty()
                || txtCelularFuncionario.getText().matches(".*\\d.*") == false || txtCep.getText().matches(".*\\d.*") == false
                || txtCidadeFuncionario.getText().isEmpty() || txtCpf.getText().matches(".*\\d.*") == false
                || txtEmailFuncionario.getText().isEmpty() || txtEstado.getSelectedItem() == "Selecione"
                || txtNivelAcessoFuncionario.getText().isEmpty() || txtNumeroFuncionario.getText().isEmpty()
                || txtRg.getText().matches(".*\\d.*") == false || txtRuaFuncionario.getText().isEmpty()
                || txtSenha.getText().isEmpty() || txtStatusFuncionario.getSelectedItem() == "Selecione"
                || txtTelefoneFuncionario.getText().matches(".*\\d.*") == false) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            funcionario = new Funcionario();

            funcionario.setCod_funcionario(Integer.parseInt(txtCodigoFuncionario.getText()));
            funcionario.setCpf_funcionario(txtCpf.getText());
            funcionario.setNivel_acesso(Integer.parseInt(txtNivelAcessoFuncionario.getText()));
            funcionario.setNome_funcionario(txtNomeFuncionario.getText());
            funcionario.setRg_funcionario(txtRg.getText());
            funcionario.setSenha(txtSenha.getText());
            if (txtStatusFuncionario.getSelectedItem() == "Ativo") {
                funcionario.setStatus(1);
            } else if (txtStatusFuncionario.getSelectedItem() == "Inativo") {
                funcionario.setStatus(0);
            }

            cont = new Contato();

            cont.setCelular_cliente(txtCelularFuncionario.getText());
            cont.setEmail(txtEmailFuncionario.getText());
            cont.setTelefone_cliente(txtTelefoneFuncionario.getText());

            end = new Endereco();

            end.setBairro(txtBairro.getText());
            end.setCep(txtCep.getText());
            end.setCidade(txtCidadeFuncionario.getText());
            end.setEstado(txtEstado.getSelectedItem().toString());
            end.setNumero(Integer.parseInt(txtNumeroFuncionario.getText()));
            end.setRua(txtRuaFuncionario.getText());

            try {
                dao.alterarFuncionario(funcionario, end, cont);
            } catch (SQLException ex) {
                Logger.getLogger(FuncionariosVIEW.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!", "Salvo", JOptionPane.PLAIN_MESSAGE);

            btnNovoFuncionario.setEnabled(true);
            limpaCampos();
            tabelaConsultaFuncionario.removeAll();

            try {
                listarFuncionarios();
            } catch (ParseException ex) {
                Logger.getLogger(FuncionariosVIEW.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        btnAlterarFuncionario.setVisible(false);
        btnSalvarFuncionario.setVisible(true);
        btnSalvarFuncionario.setEnabled(false);
        btnNovoFuncionario.setEnabled(true);
        limpaCampos();
        fechaCampos();
        fechaBotoes();
    }//GEN-LAST:event_btnAlterarFuncionarioActionPerformed

    private void btnExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFuncionarioActionPerformed
        funcionario = new Funcionario();

        funcionario.setCod_funcionario(Integer.parseInt(txtCodigoFuncionario.getText()));

        int confirm = JOptionPane.showConfirmDialog(null, "Deseja excluir o usuário " + txtNomeFuncionario.getText() + "?");

        if (confirm == 0) {
            try {
                dao.excluirFuncionario(funcionario);
            } catch (SQLException ex) {
                Logger.getLogger(FuncionariosVIEW.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Excluído com sucesso!", "Exclusão", JOptionPane.PLAIN_MESSAGE);
        }

        try {
            listarFuncionarios();
        } catch (ParseException ex) {
            Logger.getLogger(FuncionariosVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpaCampos();
        fechaBotoes();
        fechaCampos();
        btnAlterarFuncionario.setVisible(false);
        btnSalvarFuncionario.setVisible(true);
        btnNovoFuncionario.setEnabled(true);
    }//GEN-LAST:event_btnExcluirFuncionarioActionPerformed

    private void btnCancelarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFuncionarioActionPerformed
        limpaCampos();
        fechaBotoes();
        fechaCampos();

        btnAlterarFuncionario.setEnabled(false);
        btnNovoFuncionario.setEnabled(true);
        txtBuscarFuncionaro.setEnabled(true);
    }//GEN-LAST:event_btnCancelarFuncionarioActionPerformed

    private void btnSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFuncionarioActionPerformed
        if (txtNomeFuncionario.getText().isEmpty() || txtBairro.getText().isEmpty()
                || txtCelularFuncionario.getText().matches(".*\\d.*") == false || txtCep.getText().matches(".*\\d.*") == false
                || txtCidadeFuncionario.getText().isEmpty() || txtCpf.getText().matches(".*\\d.*") == false
                || txtEmailFuncionario.getText().isEmpty() || txtEstado.getSelectedItem() == "Selecione"
                || txtNivelAcessoFuncionario.getText().isEmpty() || txtNumeroFuncionario.getText().isEmpty()
                || txtRg.getText().matches(".*\\d.*") == false || txtRuaFuncionario.getText().isEmpty()
                || txtSenha.getText().isEmpty() || txtStatusFuncionario.getSelectedItem() == "Selecione"
                || txtTelefoneFuncionario.getText().matches(".*\\d.*") == false) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            funcionario = new Funcionario();

            funcionario.setCpf_funcionario(txtCpf.getText());
            funcionario.setNivel_acesso(Integer.parseInt(txtNivelAcessoFuncionario.getText()));
            funcionario.setNome_funcionario(txtNomeFuncionario.getText());
            funcionario.setRg_funcionario(txtRg.getText());
            funcionario.setSenha(txtSenha.getText());
            if (txtStatusFuncionario.getSelectedItem() == "Ativo") {
                funcionario.setStatus(1);
            } else if (txtStatusFuncionario.getSelectedItem() == "Inativo") {
                funcionario.setStatus(0);
            }

            cont = new Contato();

            cont.setCelular_cliente(txtCelularFuncionario.getText());
            cont.setEmail(txtEmailFuncionario.getText());
            cont.setTelefone_cliente(txtTelefoneFuncionario.getText());

            end = new Endereco();

            end.setBairro(txtBairro.getText());
            end.setCep(txtCep.getText());
            end.setCidade(txtCidadeFuncionario.getText());
            end.setEstado(txtEstado.getSelectedItem().toString());
            end.setNumero(Integer.parseInt(txtNumeroFuncionario.getText()));
            end.setRua(txtRuaFuncionario.getText());

            try {
                dao.salvarFuncionario(funcionario, end, cont);
            } catch (SQLException ex) {
                Logger.getLogger(FuncionariosVIEW.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!", "Salvo", JOptionPane.PLAIN_MESSAGE);

            btnNovoFuncionario.setEnabled(true);
            limpaCampos();
            fechaBotoes();
            fechaCampos();
            tabelaConsultaFuncionario.removeAll();

            try {
                listarFuncionarios();
            } catch (ParseException ex) {
                Logger.getLogger(FuncionariosVIEW.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSalvarFuncionarioActionPerformed

    private void txtBuscarFuncionaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarFuncionaroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarFuncionaroActionPerformed

    private void tabelaConsultaFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaFuncionarioMouseClicked
        String cod = tabelaConsultaFuncionario.getValueAt(tabelaConsultaFuncionario.getSelectedRow(), 0).toString();
        Usuario user = new Usuario();
        List<Funcionario> lista;

        try {

            lista = dao.buscarFuncionariosCodigo(cod);

            for (Funcionario f : lista) {

                txtCodigoFuncionario.setText(Integer.toString(f.getCod_funcionario()));

                txtCelularFuncionario.setText(f.getFuncContato().getCelular_cliente());
                txtCidadeFuncionario.setText(f.getFuncEndereco().getCidade());
                txtEmailFuncionario.setText(f.getFuncContato().getEmail());
                txtBairro.setText(f.getFuncEndereco().getBairro());
                txtNivelAcessoFuncionario.setText(Integer.toString(f.getNivel_acesso()));
                txtNomeFuncionario.setText(f.getNome_funcionario());
                txtNumeroFuncionario.setText(Integer.toString(f.getFuncEndereco().getNumero()));
                txtRuaFuncionario.setText(f.getFuncEndereco().getRua());
                if (f.getStatus() == 1) {
                    txtStatusFuncionario.setSelectedIndex(1);
                } else if (f.getStatus() == 0) {
                    txtStatusFuncionario.setSelectedIndex(2);
                }
                txtTelefoneFuncionario.setText(f.getFuncContato().getTelefone_cliente());
                txtCep.setText(f.getFuncEndereco().getCep());

                txtCpf.setText(f.getCpf_funcionario());
                txtRg.setText(f.getRg_funcionario());
                txtEstado.setSelectedItem(f.getFuncEndereco().getEstado());

                txtSenha.setText(f.getSenha());
            }

            abreCampos();

            jtpConsultaFuncionaros.setSelectedIndex(0);
            txtCpf.setEnabled(false);
            txtRg.setEnabled(false);
            btnSalvarFuncionario.setVisible(false);

            btnAlterarFuncionario.setEnabled(true);
            btnAlterarFuncionario.setVisible(true);

            btnCancelarFuncionario.setEnabled(true);
            btnExcluirFuncionario.setEnabled(true);
        } catch (ParseException ex) {
            Logger.getLogger(FuncionariosVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tabelaConsultaFuncionarioMouseClicked

    private void txtBuscarFuncionaroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarFuncionaroKeyPressed
        String nome = "%" + txtBuscarFuncionaro.getText() + "%";

        FuncionarioDAO dao = new FuncionarioDAO();

        List<Funcionario> lista;
        try {
            lista = dao.buscarFuncionarios(nome);

            DefaultTableModel table = (DefaultTableModel) tabelaConsultaFuncionario.getModel();

            table.setNumRows(0);

            for (Funcionario f : lista) {
                table.addRow(new Object[]{
                    f.getCod_funcionario(),
                    f.getNome_funcionario(),
                    f.getCpf_funcionario(),
                    f.getRg_funcionario(),
                    f.getData_admissao(),
                    f.getStatus(),
                    f.getNivel_acesso(),});
            }
        } catch (ParseException ex) {
            Logger.getLogger(FuncionariosVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBuscarFuncionaroKeyPressed

    private void btnNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFuncionarioActionPerformed
        abreCampos();
        limpaCampos();
        txtBuscarFuncionaro.setEnabled(true);
        //btnBuscar.setEnabled(false);
        btnNovoFuncionario.setEnabled(false);
        btnExcluirFuncionario.setEnabled(false);
        btnAlterarFuncionario.setVisible(false);
        btnCancelarFuncionario.setEnabled(true);
        btnSalvarFuncionario.setVisible(true);
        btnSalvarFuncionario.setEnabled(true);
    }//GEN-LAST:event_btnNovoFuncionarioActionPerformed

    private void txtTelefoneFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneFuncionarioActionPerformed

    private void txtCelularFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularFuncionarioActionPerformed

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    private void jpConsultaFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpConsultaFuncionarioMouseClicked

    }//GEN-LAST:event_jpConsultaFuncionarioMouseClicked

    private void jtpConsultaFuncionarosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtpConsultaFuncionarosStateChanged
        if (jtpConsultaFuncionaros.getSelectedIndex() == 0) {
            btnNovoFuncionario.setVisible(true);
        }
        if (jtpConsultaFuncionaros.getSelectedIndex() == 1) {
            btnNovoFuncionario.setVisible(false);
        }
    }//GEN-LAST:event_jtpConsultaFuncionarosStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarFuncionario;
    private javax.swing.JButton btnCancelarFuncionario;
    private javax.swing.JButton btnExcluirFuncionario;
    private javax.swing.JButton btnNovoFuncionario;
    private javax.swing.JButton btnSalvarFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel jpConsultaFuncionario;
    private javax.swing.JTabbedPane jtpConsultaFuncionaros;
    private javax.swing.JTable tabelaConsultaFuncionario;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBuscarFuncionaro;
    private javax.swing.JFormattedTextField txtCelularFuncionario;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidadeFuncionario;
    private javax.swing.JTextField txtCodigoFuncionario;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmailFuncionario;
    private javax.swing.JComboBox<String> txtEstado;
    private javax.swing.JTextField txtNivelAcessoFuncionario;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtNumeroFuncionario;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JTextField txtRuaFuncionario;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JComboBox<String> txtStatusFuncionario;
    private javax.swing.JFormattedTextField txtTelefoneFuncionario;
    // End of variables declaration//GEN-END:variables
}
